apiVersion: v1
kind: Service
metadata:
  name: boutique-svc
  namespace: default
spec:
  selector:
    app: boutique
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
